github_token = "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"

[graph_colors]
level1 = "13,68,41"
level2 = "1,108,49"
level3 = "38,166,65"
level4 = "57,211,83"

[text_colors]
info_color = "0,255,255"

[graph_data]
percentiles = [
    0,
    30,
    60,
    90,
]
